version: '2'

services:
    postgres_db:
        image: 'postgres:latest'
        ports:
            - 5432:5432
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: expiryteams

    redis_db:
        image: redis:alpine
        ports:
            - 6379:6379
        restart: always
